site_name: ixia-c
repo_url: https://github.com/open-traffic-generator/ixia-c
repo_name: ixia-c
edit_uri: ""
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Arial
  palette:

    # Palette toggle for light mode
    - scheme: ks-light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: ks-dark
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-traffic-generator
    - icon: fontawesome/brands/slack
      link: https://ixia-c.slack.com
# Page tree
nav:
  - Home: index.md # Needs re-writing as a landing page
  - Quick Start:
     - Introduction: quick-start/introduction.md # Now goes as Ixia-c Quick Start. Call the section to reflect that
     - Deployment: quick-start/deployment.md # Link to deployment dir is broken. Need a compose file in text. Need to move to docker compose later
     - Sample test: quick-start/sample-test.md # Empty - otgen example or hello snappi?. See "clients" in UG Intro
  - User Guide:
    - Introduction: user-guide-introduction.md # Update images. Ixia-c link leads to empty page
    - Prerequisites: prerequisites.md # Make clear when you need Python. Network Int Prereqs - do we need this at all?
    - Deployment: deployments.md # All deployments are via links, easy to miss. Do we make this top-level for Ixia-c/UHD/HW?
    - Use cases: usecases.md # Remove for now, rethink what is this later
    - Integrated environments: integrated-environments.md # A strange mix of otg-examples and clab/kne. Move Clab/KNE deployments here
    - Ixia-c tests: tests-ixia-c.md # Empty. Use otg-examples?
    - Ixia chassis/appliance tests: tests-chassis-app.md # This this HW deployment, there is no scripts (and likely should not be)
    - UHD 400 tests: tests-uhd400.md # This is UHD400 intro. Not deployment, not scripts. Need to align with HW
    - Limitations: limitations.md # Align with the DS, clarify if this is for Ixia-c/UHD/HW
    - Troubleshooting: troubleshooting.md # Move how to see logs from Deployment here
    - Releases: releases.md # Move it to the top, at the end
    - Licensing: licensing.md # Update from otg-examples
  - Developer Guide: # This section is not ready yet for publishing
    - Introduction: developer/introduction.md # Take from otg.dev?
    - Common constructs: developer/snappi-constructs.md # Cleanup TBD at the end
    - Installing snappi: developer/snappi-install.md # Split into python and go. Rename as sample scripts?
    - Using snappi: developer/hello-snappi.md # Move to quick start
  - Reference Guide:
    - Resource requirements: reference/resource-requirements.md
    - Feature gap list: reference/feature-gap-table.md
  - Leftovers:
    - News: news.md # Check if autogenerated. If yes, see how to merge with releases
    - Contributing: contribute.md # Move to Developer guide
    - EULA: eula.md # ???
    - FAQ: faq.md # Review if there are any valuable items left
    - Support: support.md # Move to home / spin into Community
