site_name: Ixia-c
repo_url: https://github.com/open-traffic-generator/ixia-c
repo_name: ixia-c
edit_uri: ""
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Arial
  palette: 

    # Palette toggle for light mode
    - scheme: ks-light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: ks-dark
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-traffic-generator
    - icon: fontawesome/brands/slack
      link: https://ixia-c.slack.com
# Page tree
nav:
  - Home: index.md
  - User Guide: 
    - Prerequisites: prerequisites.md
    - Deployment: deployments.md
    - Limitations: limitations.md
    - Contributing: contribute.md
    - EULA: eula.md
  - Developer Guide:
    - Hello, snappi: hello-snappi.md
    - Common constructs: snappi-constructs.md
  - FAQ: faq.md
  - Releases:
    - News: news.md
    - Versions: releases.md
  - Support: support.md



