site_name: Ixia-c & Elastic Network Generator Documentation
repo_url: https://github.com/open-traffic-generator/ixia-c
repo_name: ixia-c
edit_uri: ""
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Arial
  palette:
    # Palette toggle for light mode
    - scheme: ks-light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: ks-dark
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-L42048L6R5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-traffic-generator
    - icon: fontawesome/brands/slack
      link: https://ixia-c.slack.com
# Page tree
nav:
  - Home:
    - Overview: index.md # Needs re-writing as a landing page
#    - FAQ: faq.md # Review if there are any valuable items left
    - Resources: resources.md
    - EULA: eula.md # Updated to use www.keysight.com/find/sweula
  - Quick Start:
    - Introduction: quick-start/introduction.md # Now goes as Ixia-c Quick Start. Add a paragraph why
#    - Deployment: quick-start/deployment.md # Link to deployment dir is broken. Need a compose file in text. Need to move to docker compose later
#    - Sample test: quick-start/sample-test.md # Empty - otgen example or hello snappi?. See "clients" in UG Intro
    - First script: developer/hello-snappi.md # Took from Developer Guide
  - User Guide:
    - Introduction: user-guide-introduction.md # Update images. Ixia-c link leads to empty page
    - Prerequisites: prerequisites.md # Make clear when you need Python. Network Int Prereqs - do we need this at all?
    - Deployment:
      - Ixia-c: deployments.md # All deployments are via links, easy to miss. Do we make this top-level for Ixia-c/UHD/HW?
      - UHD400T: tests-uhd400.md # This is UHD400 intro. Not deployment, not scripts. Need to align with HW
      - IxOS Hardware: tests-chassis-app.md # This this HW deployment, there is no scripts (and likely should not be)
#    - Use cases: usecases.md # Remove for now, rethink what is this later
    - Integrations: integrated-environments.md # A strange mix of otg-examples and clab/kne. Move Clab/KNE deployments here
    - Limitations: limitations.md # Align with the DS, clarify if this is for Ixia-c/UHD/HW
    - Troubleshooting: troubleshooting.md # Move how to see logs from Deployment here
    - Licensing: licensing.md # Update from otg-examples
  - Developer Guide: # This section is not ready yet for publishing
#    - Introduction: developer/introduction.md # Take from otg.dev?
    - Python with snappi: developer/snappi-constructs.md # Cleanup TBD at the end
    - Go with gosnappi: developer/snappi-install.md # Split into python and go. Rename as sample scripts?
    - Contributing: contribute.md # Move to Developer guide
  - Reference Guide:
    - Capabilities: reference/capabilities.md
    - Resource requirements: reference/resource-requirements.md
    - Licensing: reference/licensing.md
  - Releases:
    - Releases: releases.md
    - Announcements: news.md # Check if autogenerated. If yes, see how to merge with releases
  - Support: support.md
