site_name: ixia-c
repo_url: https://github.com/open-traffic-generator/ixia-c
repo_name: ixia-c
edit_uri: ""
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Arial
  palette:

    # Palette toggle for light mode
    - scheme: ks-light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: ks-dark
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-traffic-generator
    - icon: fontawesome/brands/slack
      link: https://ixia-c.slack.com
# Page tree
nav:
  - Home: index.md
  - Quick Start:
     - Introduction: quick-start/introduction.md
     - Deployment: quick-start/deployment.md
     - Sample test: quick-start/sample-test.md
  - User Guide:
    - Introduction: user-guide-introduction.md
    - Prerequisites: prerequisites.md
    - Deployment: deployments.md
    - Use cases: usecases.md
    - Integrated environments: integrated-environments.md
    - Ixia-c tests: tests-ixia-c.md
    - Ixia chassis/appliance tests: tests-chassis-app.md
    - UHD 400 tests: tests-uhd400.md
    - Limitations: limitations.md
    - Troubleshooting: troubleshooting.md
    - Releases: releases.md
    - Licensing: licensing.md
  - Developer Guide:
    - Introduction: developer/introduction.md
    - Common constructs: developer/snappi-constructs.md
    - Installing snappi: developer/snappi-install.md
    - Using snappi: developer/hello-snappi.md
  - Reference Guide:
    - Resource requirements: reference/resource-requirements.md
    - Feature gap list: reference/feature-gap-table.md
  - Leftovers:
    - News: news.md
    - Contributing: contribute.md
    - EULA: eula.md
    - FAQ: faq.md
    - Support: support.md
