apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Release: https://github.com/open-traffic-generator/ixia-c/releases/tag/v1.44.0-8
images:
  - name: keng-controller
    newName: ghcr.io/open-traffic-generator/keng-controller
    newTag: "1.44.0-8"
  - name: otg-gnmi-server
    newName: ghcr.io/open-traffic-generator/otg-gnmi-server
    newTag: "1.44.1"
  - name: ixia-c-traffic-engine
    newName: ghcr.io/open-traffic-generator/ixia-c-traffic-engine
    newTag: "1.8.0.245"
