apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Release: https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.0.1-3882
images:
  - name: ixia-c-controller
    newName: ghcr.io/open-traffic-generator/ixia-c-controller
    newTag: "0.0.1-3889"
  - name: ixia-c-gnmi-server
    newName: ghcr.io/open-traffic-generator/ixia-c-gnmi-server
    newTag: "1.11.8"
  - name: ixia-c-traffic-engine
    newName: ghcr.io/open-traffic-generator/ixia-c-traffic-engine
    newTag: "1.6.0.35"
