release: 1.44.0-8
open-traffic-generator: 1.44.0
snappi: 1.44.0
gosnappi: 1.44.0
keng-controller: 1.44.0-8
ixia-c-traffic-engine: 1.8.0.245
ixia-c-protocol-engine: 1.00.0.501
otg-gnmi-server: 1.44.1
keng-operator: 0.3.34
keng-layer23-hw-server: 1.44.0-8
keng-app-usage-reporter: 0.0.1-52
ixia-c-one: 1.44.0-8
uhd400: 1.5.10
